apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-deployment
  labels:
    app: dog-pic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dog-pic
  template:
    metadata:
      labels:
        app: dog-pic
    spec:
      containers:
      - name: dog-pic
        image: ajs3ra8/akash-app:0.0.6
        ports:
        - containerPort: 80
